# Credit Card Fraud Detection

- Build a machine learning model to indentify fraudulent credit card transactions.
- Preprocess and normalize the transaction data, handle class imbalance issues, and split the dataset into training and testing sets.
- Train a classification algorithm, such as a logistic regression, to classify transactions as fraudulent or genuine.
- Evaluate the model.

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# Load the dataset
cc_data = pd.read_csv('creditcard.csv')

In [3]:
cc_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
cc_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
# Dataset Information
cc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# Check the null values present or not
cc_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# Distribution of legit and fraudulent transactions
cc_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Here the data is imbalanced

In [8]:
# Split the data
legit = cc_data[cc_data.Class == 0]

In [9]:
fraud = cc_data[cc_data.Class == 1]

In [10]:
legit

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [11]:
fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [12]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [13]:
# Statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [14]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [15]:
# Compare the values of both transactions
cc_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [16]:
# Under sampling
legit_sample = legit.sample(n=492)

In [17]:
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
91589,63541.0,1.572525,-0.900419,-0.505869,-1.636163,-0.724245,-0.575838,-0.602231,-0.191884,-2.313494,...,-0.180857,-0.180323,-0.190528,-0.514825,0.741096,-0.047308,-0.011995,-0.013057,15.00,0
253485,156272.0,0.013591,-2.334082,-2.722611,-2.370500,0.990827,4.226895,0.387787,-0.134392,-0.266019,...,1.656881,1.414657,0.381649,0.782014,0.030226,-0.003607,0.213222,0.437579,550.00,0
36944,38746.0,-0.287052,0.691460,1.207811,0.461109,0.195498,-0.060675,0.516207,0.116509,-0.856638,...,0.226378,0.632819,-0.033852,0.051195,-0.589960,0.446419,0.131300,0.147589,27.95,0
221623,142636.0,-0.905143,-0.541502,0.193214,-0.544106,1.923136,-1.299216,0.849250,-0.613995,0.267077,...,-0.060384,0.116453,-0.002907,-0.335259,-0.684728,-0.208578,-0.577721,0.132777,0.00,0
263762,161104.0,-1.102416,0.174193,-0.656259,-0.204375,1.462132,-1.262375,1.048909,-0.519836,0.655611,...,0.023285,0.941223,0.322680,-0.757844,-0.254106,-0.114045,0.157008,-0.061310,11.94,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281951,170556.0,2.022367,-0.654734,-0.911969,-0.930467,-0.312133,-0.301213,-0.466449,-0.181205,1.359699,...,0.164109,0.648117,-0.005623,-0.939499,-0.171626,0.762152,-0.033273,-0.050971,55.00,0
265068,161724.0,2.070863,0.012639,-1.236749,0.368520,-0.052184,-1.331288,0.232968,-0.411974,0.576321,...,0.264257,0.953594,-0.003228,0.095271,0.266076,-0.105671,-0.013506,-0.056656,1.00,0
206046,136043.0,2.007323,0.233686,-1.086013,1.929066,0.247330,-0.917747,0.431006,-0.407641,-0.988361,...,-0.180554,-0.491501,0.279618,0.157228,-0.440563,2.097334,-0.220679,-0.081450,26.55,0
176908,122961.0,1.791096,-0.199775,-1.992649,1.377250,0.290541,-1.412338,0.875649,-0.446923,0.103187,...,0.190939,0.270357,-0.108073,-0.055469,0.346377,-0.490086,-0.066960,-0.043517,144.00,0
210020,137806.0,1.946176,-0.285794,-1.129450,0.539553,-0.157667,-0.087052,-0.601154,0.185340,1.044302,...,0.135847,0.594423,0.100348,0.648136,-0.121036,0.622661,-0.028799,-0.033155,10.00,0

In [18]:
# concat the both datasets
new_df = pd.concat([legit_sample, fraud], axis = 0)

In [19]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
91589,63541.0,1.572525,-0.900419,-0.505869,-1.636163,-0.724245,-0.575838,-0.602231,-0.191884,-2.313494,...,-0.180857,-0.180323,-0.190528,-0.514825,0.741096,-0.047308,-0.011995,-0.013057,15.00,0
253485,156272.0,0.013591,-2.334082,-2.722611,-2.370500,0.990827,4.226895,0.387787,-0.134392,-0.266019,...,1.656881,1.414657,0.381649,0.782014,0.030226,-0.003607,0.213222,0.437579,550.00,0
36944,38746.0,-0.287052,0.691460,1.207811,0.461109,0.195498,-0.060675,0.516207,0.116509,-0.856638,...,0.226378,0.632819,-0.033852,0.051195,-0.589960,0.446419,0.131300,0.147589,27.95,0
221623,142636.0,-0.905143,-0.541502,0.193214,-0.544106,1.923136,-1.299216,0.849250,-0.613995,0.267077,...,-0.060384,0.116453,-0.002907,-0.335259,-0.684728,-0.208578,-0.577721,0.132777,0.00,0
263762,161104.0,-1.102416,0.174193,-0.656259,-0.204375,1.462132,-1.262375,1.048909,-0.519836,0.655611,...,0.023285,0.941223,0.322680,-0.757844,-0.254106,-0.114045,0.157008,-0.061310,11.94,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [20]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [21]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96674.351626,-0.073858,-0.135243,0.010495,-0.000474,0.032461,0.041236,0.034430,0.001776,-0.000974,...,0.078480,-0.011062,-0.020396,0.013407,0.000025,-0.027930,-0.001767,-0.028001,-0.023208,108.501118
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [22]:
# Splitting the data into features and target variables
X = new_df.drop(columns = 'Class', axis = 1)
y = new_df['Class']

In [23]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
91589,63541.0,1.572525,-0.900419,-0.505869,-1.636163,-0.724245,-0.575838,-0.602231,-0.191884,-2.313494,...,-0.341308,-0.180857,-0.180323,-0.190528,-0.514825,0.741096,-0.047308,-0.011995,-0.013057,15.00
253485,156272.0,0.013591,-2.334082,-2.722611,-2.370500,0.990827,4.226895,0.387787,-0.134392,-0.266019,...,0.877306,1.656881,1.414657,0.381649,0.782014,0.030226,-0.003607,0.213222,0.437579,550.00
36944,38746.0,-0.287052,0.691460,1.207811,0.461109,0.195498,-0.060675,0.516207,0.116509,-0.856638,...,0.085040,0.226378,0.632819,-0.033852,0.051195,-0.589960,0.446419,0.131300,0.147589,27.95
221623,142636.0,-0.905143,-0.541502,0.193214,-0.544106,1.923136,-1.299216,0.849250,-0.613995,0.267077,...,-0.007276,-0.060384,0.116453,-0.002907,-0.335259,-0.684728,-0.208578,-0.577721,0.132777,0.00
263762,161104.0,-1.102416,0.174193,-0.656259,-0.204375,1.462132,-1.262375,1.048909,-0.519836,0.655611,...,-0.541511,0.023285,0.941223,0.322680,-0.757844,-0.254106,-0.114045,0.157008,-0.061310,11.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [24]:
y

91589     0
253485    0
36944     0
221623    0
263762    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [25]:
# Split the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 2)

In [26]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [27]:
print(y.shape, y_train.shape, y_test.shape)

(984,) (787,) (197,)

In [28]:
# Model train - logistic regression

In [29]:
model = LogisticRegression( max_iter = 1000000)

In [30]:
# training of model
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000000)

In [31]:
# Model Evaluation
# Accuracy score
X_train_pred = model.predict(X_train)

In [32]:
training_accuracy = accuracy_score(X_train_pred, y_train)

In [33]:
print('Accuracy Score of Training model :', training_accuracy)

Accuracy Score of Training model : 0.9567979669631512

In [34]:
X_test_pred = model.predict(X_test)

In [35]:
testing_accuracy = accuracy_score(X_test_pred, y_test)

In [36]:
print('Accuracy Score of Testing model :', testing_accuracy)

Accuracy Score of Testing model : 0.9187817258883249

In [37]:
import pickle

pickle.dump(model, open("cc_fraud.pkl", "wb"))