# Credit Card Fraud Detection

- Build a machine learning model to indentify fraudulent credit card transactions.
- Preprocess and normalize the transaction data, handle class imbalance issues, and split the dataset into training and testing sets.
- Train a classification algorithm, such as a logistic regression, to classify transactions as fraudulent or genuine.
- Evaluate the model.

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
# Load the dataset
cc_data = pd.read_csv('creditcard.csv')

In [4]:
cc_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
cc_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
# Dataset Information
cc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
# Check the null values present or not
cc_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
# Distribution of legit and fraudulent transactions
cc_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Here the data is imbalanced

In [10]:
# Split the data
legit = cc_data[cc_data.Class == 0]

In [11]:
fraud = cc_data[cc_data.Class == 1]

In [12]:
legit

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [13]:
fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [14]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [15]:
# Statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [16]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [17]:
# Compare the values of both transactions
cc_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [18]:
# Under sampling
legit_sample = legit.sample(n=492)

In [19]:
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125089,77531.0,-1.550961,-1.432970,2.598600,-1.508964,0.172255,0.274792,-1.107065,0.582199,-0.405690,...,0.401827,0.966126,-0.188224,-0.244731,0.667798,-0.091655,0.029949,0.065120,50.35,0
142742,84908.0,1.317510,-0.030097,-1.088762,-0.557973,2.031006,3.267737,-0.536440,0.808533,-0.052596,...,-0.313968,-1.068359,0.104757,0.992070,0.369798,0.110490,-0.028096,0.011647,0.89,0
154266,100950.0,2.047755,-0.022368,-0.946709,0.624352,-0.119043,-1.101069,0.024394,-0.341782,1.955084,...,-0.441264,-0.934566,0.365365,-0.097651,-0.367296,0.164906,-0.100724,-0.068032,5.99,0
176992,122993.0,-2.372765,2.050996,-0.018349,-1.729788,0.063170,0.442717,0.022890,0.116307,1.682692,...,-0.132039,-0.619076,-0.084032,-1.436813,0.012558,-0.347029,-1.233848,-0.052811,0.77,0
12983,22808.0,-1.380285,1.235735,2.265905,1.888380,-1.069035,1.559450,-0.383276,-2.260760,1.860100,...,1.764367,-1.387059,-0.310907,0.364246,-0.239288,-0.433951,0.467802,0.083912,190.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84755,60447.0,1.232507,0.157845,0.012013,1.082744,-0.050762,-0.417626,0.084325,-0.096219,0.197898,...,0.021990,-0.001747,-0.227852,-0.478231,0.738838,-0.228256,0.004599,0.016627,35.10,0
126565,78031.0,-0.305785,0.295722,2.045270,-0.922724,-0.671933,-0.380864,-0.080856,0.131162,1.096782,...,0.175420,0.799669,-0.044802,0.440872,-0.549462,-0.685319,0.272592,0.181167,1.00,0
238108,149524.0,1.885597,-0.944890,-0.796074,-0.142870,-0.918704,-0.949978,-0.218211,-0.306050,-0.221984,...,-0.757652,-1.863531,0.461490,-0.058689,-0.613820,-0.885889,0.014636,-0.008751,130.44,0
212146,138735.0,2.062659,-1.010186,-1.134954,-0.663691,-0.439072,0.197353,-0.762610,0.053663,-0.366476,...,-0.335756,-0.524279,0.206045,0.084747,-0.326461,0.540410,-0.051391,-0.053465,55.50,0
77912,57275.0,1.298182,0.184086,-0.184392,0.205036,-0.033440,-0.954630,0.341483,-0.323434,-0.041850,...,-0.082907,-0.218530,-0.134566,-0.050113,0.597356,0.628147,-0.070493,0.001101,23.00,0

In [20]:
# concat the both datasets
new_df = pd.concat([legit_sample, fraud], axis = 0)

In [21]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125089,77531.0,-1.550961,-1.432970,2.598600,-1.508964,0.172255,0.274792,-1.107065,0.582199,-0.405690,...,0.401827,0.966126,-0.188224,-0.244731,0.667798,-0.091655,0.029949,0.065120,50.35,0
142742,84908.0,1.317510,-0.030097,-1.088762,-0.557973,2.031006,3.267737,-0.536440,0.808533,-0.052596,...,-0.313968,-1.068359,0.104757,0.992070,0.369798,0.110490,-0.028096,0.011647,0.89,0
154266,100950.0,2.047755,-0.022368,-0.946709,0.624352,-0.119043,-1.101069,0.024394,-0.341782,1.955084,...,-0.441264,-0.934566,0.365365,-0.097651,-0.367296,0.164906,-0.100724,-0.068032,5.99,0
176992,122993.0,-2.372765,2.050996,-0.018349,-1.729788,0.063170,0.442717,0.022890,0.116307,1.682692,...,-0.132039,-0.619076,-0.084032,-1.436813,0.012558,-0.347029,-1.233848,-0.052811,0.77,0
12983,22808.0,-1.380285,1.235735,2.265905,1.888380,-1.069035,1.559450,-0.383276,-2.260760,1.860100,...,1.764367,-1.387059,-0.310907,0.364246,-0.239288,-0.433951,0.467802,0.083912,190.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [22]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [23]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95856.386179,0.113631,0.017843,0.039995,-0.075802,-0.025964,0.046516,0.017345,0.031356,0.085724,...,0.013833,0.005600,-0.027256,0.011935,-0.007194,-0.031105,0.021051,0.023582,0.009832,88.485081
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [24]:
# Splitting the data into features and target variables
X = new_df.drop(columns = 'Class', axis = 1)
y = new_df['Class']

In [25]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
125089,77531.0,-1.550961,-1.432970,2.598600,-1.508964,0.172255,0.274792,-1.107065,0.582199,-0.405690,...,0.354623,0.401827,0.966126,-0.188224,-0.244731,0.667798,-0.091655,0.029949,0.065120,50.35
142742,84908.0,1.317510,-0.030097,-1.088762,-0.557973,2.031006,3.267737,-0.536440,0.808533,-0.052596,...,0.014732,-0.313968,-1.068359,0.104757,0.992070,0.369798,0.110490,-0.028096,0.011647,0.89
154266,100950.0,2.047755,-0.022368,-0.946709,0.624352,-0.119043,-1.101069,0.024394,-0.341782,1.955084,...,-0.320675,-0.441264,-0.934566,0.365365,-0.097651,-0.367296,0.164906,-0.100724,-0.068032,5.99
176992,122993.0,-2.372765,2.050996,-0.018349,-1.729788,0.063170,0.442717,0.022890,0.116307,1.682692,...,0.299648,-0.132039,-0.619076,-0.084032,-1.436813,0.012558,-0.347029,-1.233848,-0.052811,0.77
12983,22808.0,-1.380285,1.235735,2.265905,1.888380,-1.069035,1.559450,-0.383276,-2.260760,1.860100,...,-0.725527,1.764367,-1.387059,-0.310907,0.364246,-0.239288,-0.433951,0.467802,0.083912,190.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [26]:
y

125089    0
142742    0
154266    0
176992    0
12983     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [27]:
# Split the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 2)

In [29]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [30]:
print(y.shape, y_train.shape, y_test.shape)

(984,) (787,) (197,)

In [31]:
# Model train - logistic regression

In [33]:
model = LogisticRegression( max_iter = 1000000)

In [34]:
# training of model
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000000)

In [35]:
# Model Evaluation
# Accuracy score
X_train_pred = model.predict(X_train)

In [37]:
training_accuracy = accuracy_score(X_train_pred, y_train)

In [38]:
print('Accuracy Score of Training model :', training_accuracy)

Accuracy Score of Training model : 0.9618805590851334

In [39]:
X_test_pred = model.predict(X_test)

In [40]:
testing_accuracy = accuracy_score(X_test_pred, y_test)

In [41]:
print('Accuracy Score of Testing model :', testing_accuracy)

Accuracy Score of Testing model : 0.9035532994923858

In [42]:
import joblib

joblib.dump(model, 'cc_fraud.pkl')

['cc_fraud.pkl']